version: "3.8"

services:
  web:
    image: "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
    container_name: web
    ports:
      - "5000:5000"
    environment:
      - DAGSHUB_TOKEN=${DAGSHUB_TOKEN}
    networks:
      - sleep
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sleep
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:

networks:
  sleep:
    driver: bridge
